# Devlopment docker-compose file.
# Should be the same as docker-compose.yml except that the project should be
# mounted to the docker container for easy development

version: "3"
services:
    app:
        build: .
        restart: always
        ports:
            - "8000:8000"
        command: sh -c "sleep 10s ; gunicorn -w4 -b 0.0.0.0:8000 --reload app:app"
        volumes:
            - .:/app
        env_file:
            - src/.env
        dns:
            - 1.1.1.1
        depends_on:
            - mysql

    mysql:
        image: docker.io/mysql:latest
        env_file:
            - src/.env
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: always
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
            timeout: 10s
            retries: 5
        hostname: mysql

volumes:
    mysql_data:
